// <auto-generated />
using System;
using ClinicalIntelligence.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace ClinicalIntelligence.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260116122429_AddPgvectorExtension")]
    partial class AddPgvectorExtension
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ClinicalIntelligence.Api.Domain.Models.AuditLogEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("IntegrityHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("ResourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResourceType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ActionType")
                        .HasDatabaseName("ix_audit_log_events_action_type");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_audit_log_events_session_id");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("ix_audit_log_events_timestamp");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_audit_log_events_user_id");

                    b.HasIndex("ResourceType", "ResourceId")
                        .HasDatabaseName("ix_audit_log_events_resource");

                    b.ToTable("audit_log_events", (string)null);
                });

            modelBuilder.Entity("ClinicalIntelligence.Api.Domain.Models.BillingCodeCatalogItem", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("CodeType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Code");

                    b.HasIndex("CodeType")
                        .HasDatabaseName("ix_billing_code_catalog_items_code_type");

                    b.ToTable("billing_code_catalog_items", (string)null);
                });

            modelBuilder.Entity("ClinicalIntelligence.Api.Domain.Models.CodeSuggestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("CodeType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("DecidedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DecidedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ExtractedEntityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceText")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("SuggestedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .HasDatabaseName("ix_code_suggestions_code");

                    b.HasIndex("DecidedByUserId");

                    b.HasIndex("ExtractedEntityId")
                        .HasDatabaseName("ix_code_suggestions_extracted_entity_id");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_code_suggestions_patient_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_code_suggestions_status");

                    b.ToTable("code_suggestions", (string)null);
                });

            modelBuilder.Entity("ClinicalIntelligence.Api.Domain.Models.Condition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AbatementDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ClinicalStatus")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Code")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CodeDisplay")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("EncounterId")
                        .HasColumnType("uuid");

                    b.Property<string>("Extensions")
                        .HasColumnType("text");

                    b.Property<DateTime?>("OnsetDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<string>("Severity")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("VerificationStatus")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .HasDatabaseName("ix_conditions_code");

                    b.HasIndex("EncounterId")
                        .HasDatabaseName("ix_conditions_encounter_id");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_conditions_patient_id");

                    b.ToTable("conditions", (string)null);
                });

            modelBuilder.Entity("ClinicalIntelligence.Api.Domain.Models.ConflictResolution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConflictId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ResolvedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("ResolvedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResolvedValue")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ConflictId")
                        .IsUnique()
                        .HasDatabaseName("ix_conflict_resolutions_conflict_id");

                    b.HasIndex("ResolvedByUserId")
                        .HasDatabaseName("ix_conflict_resolutions_resolved_by_user_id");

                    b.ToTable("conflict_resolutions", (string)null);
                });

            modelBuilder.Entity("ClinicalIntelligence.Api.Domain.Models.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DocumentBatchId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("OriginalName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<int>("SizeBytes")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("UploadedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DocumentBatchId")
                        .HasDatabaseName("ix_documents_document_batch_id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_documents_is_deleted");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_documents_patient_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_documents_status");

                    b.HasIndex("UploadedByUserId");

                    b.HasIndex("PatientId", "UploadedAt")
                        .HasDatabaseName("ix_documents_patient_id_uploaded_at");

                    b.ToTable("documents", (string)null);
                });

            modelBuilder.Entity("ClinicalIntelligence.Api.Domain.Models.DocumentBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("UploadedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_document_batches_patient_id");

                    b.HasIndex("UploadedAt")
                        .HasDatabaseName("ix_document_batches_uploaded_at");

                    b.HasIndex("UploadedByUserId")
                        .HasDatabaseName("ix_document_batches_uploaded_by_user_id");

                    b.ToTable("document_batches", (string)null);
                });

            modelBuilder.Entity("ClinicalIntelligence.Api.Domain.Models.DocumentChunk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChunkHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Coordinates")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(768)");

                    b.Property<int?>("Page")
                        .HasColumnType("integer");

                    b.Property<string>("Section")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TextContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TokenCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChunkHash")
                        .HasDatabaseName("ix_document_chunks_chunk_hash");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("ix_document_chunks_document_id");

                    b.ToTable("document_chunks", (string)null);
                });

            modelBuilder.Entity("ClinicalIntelligence.Api.Domain.Models.DocumentReference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Extensions")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("OriginalName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProcessingStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Type")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_document_references_is_deleted");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_document_references_patient_id");

                    b.HasIndex("ProcessingStatus")
                        .HasDatabaseName("ix_document_references_processing_status");

                    b.ToTable("document_references", (string)null);
                });

            modelBuilder.Entity("ClinicalIntelligence.Api.Domain.Models.Encounter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Class")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Extensions")
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReasonCode")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Type")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_encounters_patient_id");

                    b.HasIndex("StartDate")
                        .HasDatabaseName("ix_encounters_start_date");

                    b.ToTable("encounters", (string)null);
                });

            modelBuilder.Entity("ClinicalIntelligence.Api.Domain.Models.EntityCitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CitedText")
                        .HasColumnType("text");

                    b.Property<string>("Coordinates")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("DocumentChunkId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExtractedEntityId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Page")
                        .HasColumnType("integer");

                    b.Property<string>("Section")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentChunkId")
                        .HasDatabaseName("ix_entity_citations_document_chunk_id");

                    b.HasIndex("ExtractedEntityId")
                        .HasDatabaseName("ix_entity_citations_extracted_entity_id");

                    b.ToTable("entity_citations", (string)null);
                });

            modelBuilder.Entity("ClinicalIntelligence.Api.Domain.Models.ErdConflict", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConflictingValues")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("DetectedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("EntityCategory")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_conflicts_patient_id");

                    b.HasIndex("Severity")
                        .HasDatabaseName("ix_conflicts_severity");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_conflicts_status");

                    b.ToTable("conflicts", (string)null);
                });

            modelBuilder.Entity("ClinicalIntelligence.Api.Domain.Models.ErdPatient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Contact")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("Dob")
                        .HasColumnType("date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Mrn")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_erd_patients_is_deleted");

                    b.HasIndex("Mrn")
                        .IsUnique()
                        .HasDatabaseName("ix_erd_patients_mrn");

                    b.ToTable("erd_patients", (string)null);
                });

            modelBuilder.Entity("ClinicalIntelligence.Api.Domain.Models.ExtractedEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<float?>("ConfidenceScore")
                        .HasColumnType("real");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EffectiveAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<string>("Units")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Value")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("VerifiedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Category")
                        .HasDatabaseName("ix_extracted_entities_category");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("ix_extracted_entities_document_id");

                    b.HasIndex("IsVerified")
                        .HasDatabaseName("ix_extracted_entities_is_verified");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_extracted_entities_patient_id");

                    b.HasIndex("VerifiedByUserId");

                    b.ToTable("extracted_entities", (string)null);
                });

            modelBuilder.Entity("ClinicalIntelligence.Api.Domain.Models.FhirResourceLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("FhirResourceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FhirResourceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FhirResourceUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("FhirVersion")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<Guid>("InternalEntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("InternalEntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceSystem")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("SourceSystem")
                        .HasDatabaseName("ix_fhir_resource_links_source_system");

                    b.HasIndex("InternalEntityType", "InternalEntityId")
                        .HasDatabaseName("ix_fhir_resource_links_internal_entity");

                    b.HasIndex("FhirResourceType", "FhirResourceId", "FhirVersion")
                        .HasDatabaseName("ix_fhir_resource_links_fhir_resource");

                    b.ToTable("fhir_resource_links", (string)null);
                });

            modelBuilder.Entity("ClinicalIntelligence.Api.Domain.Models.MedicationStatement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Dosage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("EffectiveDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Extensions")
                        .HasColumnType("text");

                    b.Property<string>("Frequency")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MedicationCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MedicationName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReasonCode")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Route")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("MedicationCode")
                        .HasDatabaseName("ix_medication_statements_medication_code");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_medication_statements_patient_id");

                    b.ToTable("medication_statements", (string)null);
                });

            modelBuilder.Entity("ClinicalIntelligence.Api.Domain.Models.Observation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CodeDisplay")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("EffectiveDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EncounterId")
                        .HasColumnType("uuid");

                    b.Property<string>("Extensions")
                        .HasColumnType("text");

                    b.Property<string>("Interpretation")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReferenceRangeHigh")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ReferenceRangeLow")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Value")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .HasDatabaseName("ix_observations_code");

                    b.HasIndex("EffectiveDate")
                        .HasDatabaseName("ix_observations_effective_date");

                    b.HasIndex("EncounterId")
                        .HasDatabaseName("ix_observations_encounter_id");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_observations_patient_id");

                    b.ToTable("observations", (string)null);
                });

            modelBuilder.Entity("ClinicalIntelligence.Api.Domain.Models.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .HasDatabaseName("ix_password_reset_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_password_reset_tokens_user_id");

                    b.ToTable("password_reset_tokens", (string)null);
                });

            modelBuilder.Entity("ClinicalIntelligence.Api.Domain.Models.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Extensions")
                        .HasColumnType("text");

                    b.Property<string>("FamilyName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("GivenName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Mrn")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_patients_is_deleted");

                    b.HasIndex("Mrn")
                        .IsUnique()
                        .HasDatabaseName("ix_patients_mrn")
                        .HasFilter("\"Mrn\" IS NOT NULL");

                    b.HasIndex("FamilyName", "GivenName", "DateOfBirth")
                        .HasDatabaseName("ix_patients_name_dob");

                    b.ToTable("patients", (string)null);
                });

            modelBuilder.Entity("ClinicalIntelligence.Api.Domain.Models.Procedure", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BodySite")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Code")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CodeDisplay")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("EncounterId")
                        .HasColumnType("uuid");

                    b.Property<string>("Extensions")
                        .HasColumnType("text");

                    b.Property<string>("Outcome")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("PerformedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("PerformedEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReasonCode")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .HasDatabaseName("ix_procedures_code");

                    b.HasIndex("EncounterId")
                        .HasDatabaseName("ix_procedures_encounter_id");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_procedures_patient_id");

                    b.ToTable("procedures", (string)null);
                });

            modelBuilder.Entity("ClinicalIntelligence.Api.Domain.Models.ProcessingJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<string>("ErrorDetails")
                        .HasColumnType("jsonb");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<int?>("ProcessingTimeMs")
                        .HasColumnType("integer");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("ix_processing_jobs_document_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_processing_jobs_status");

                    b.ToTable("processing_jobs", (string)null);
                });

            modelBuilder.Entity("ClinicalIntelligence.Api.Domain.Models.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CsrfTokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastActivityAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_sessions_expires_at");

                    b.HasIndex("IsRevoked")
                        .HasDatabaseName("ix_sessions_is_revoked");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_sessions_user_id");

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("ClinicalIntelligence.Api.Domain.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsStaticAdmin")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_users_is_deleted");

                    b.HasIndex("IsStaticAdmin")
                        .HasDatabaseName("ix_users_is_static_admin");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_users_status");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("ClinicalIntelligence.Api.Domain.Models.VectorQueryLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<string>("QueryHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("QueryText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ResponseTimeMs")
                        .HasColumnType("integer");

                    b.Property<int>("ResultCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_vector_query_logs_patient_id");

                    b.HasIndex("QueryHash")
                        .HasDatabaseName("ix_vector_query_logs_query_hash");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("ix_vector_query_logs_timestamp");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_vector_query_logs_user_id");

                    b.ToTable("vector_query_logs", (string)null);
                });

            modelBuilder.Entity("ClinicalIntelligence.Api.Domain.Models.AuditLogEvent", b =>
                {
                    b.HasOne("ClinicalIntelligence.Api.Domain.Models.Session", "Session")
                        .WithMany("AuditLogEvents")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ClinicalIntelligence.Api.Domain.Models.User", "User")
                        .WithMany("AuditLogEvents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Session");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClinicalIntelligence.Api.Domain.Models.CodeSuggestion", b =>
                {
                    b.HasOne("ClinicalIntelligence.Api.Domain.Models.BillingCodeCatalogItem", "BillingCodeCatalogItem")
                        .WithMany("CodeSuggestions")
                        .HasForeignKey("Code")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClinicalIntelligence.Api.Domain.Models.User", "DecidedByUser")
                        .WithMany("CodeDecisions")
                        .HasForeignKey("DecidedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ClinicalIntelligence.Api.Domain.Models.ExtractedEntity", "ExtractedEntity")
                        .WithMany("CodeSuggestions")
                        .HasForeignKey("ExtractedEntityId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ClinicalIntelligence.Api.Domain.Models.ErdPatient", "Patient")
                        .WithMany("CodeSuggestions")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_code_suggestions_patient_id");

                    b.Navigation("BillingCodeCatalogItem");

                    b.Navigation("DecidedByUser");

                    b.Navigation("ExtractedEntity");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("ClinicalIntelligence.Api.Domain.Models.Condition", b =>
                {
                    b.HasOne("ClinicalIntelligence.Api.Domain.Models.Encounter", "Encounter")
                        .WithMany("Conditions")
                        .HasForeignKey("EncounterId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ClinicalIntelligence.Api.Domain.Models.Patient", "Patient")
                        .WithMany("Conditions")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Encounter");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("ClinicalIntelligence.Api.Domain.Models.ConflictResolution", b =>
                {
                    b.HasOne("ClinicalIntelligence.Api.Domain.Models.ErdConflict", "Conflict")
                        .WithOne("Resolution")
                        .HasForeignKey("ClinicalIntelligence.Api.Domain.Models.ConflictResolution", "ConflictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicalIntelligence.Api.Domain.Models.User", "ResolvedByUser")
                        .WithMany("ConflictResolutions")
                        .HasForeignKey("ResolvedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conflict");

                    b.Navigation("ResolvedByUser");
                });

            modelBuilder.Entity("ClinicalIntelligence.Api.Domain.Models.Document", b =>
                {
                    b.HasOne("ClinicalIntelligence.Api.Domain.Models.DocumentBatch", "DocumentBatch")
                        .WithMany("Documents")
                        .HasForeignKey("DocumentBatchId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ClinicalIntelligence.Api.Domain.Models.ErdPatient", "Patient")
                        .WithMany("Documents")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_documents_patient_id");

                    b.HasOne("ClinicalIntelligence.Api.Domain.Models.User", "UploadedByUser")
                        .WithMany("UploadedDocuments")
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DocumentBatch");

                    b.Navigation("Patient");

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("ClinicalIntelligence.Api.Domain.Models.DocumentBatch", b =>
                {
                    b.HasOne("ClinicalIntelligence.Api.Domain.Models.ErdPatient", "Patient")
                        .WithMany("DocumentBatches")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_document_batches_patient_id");

                    b.HasOne("ClinicalIntelligence.Api.Domain.Models.User", "UploadedByUser")
                        .WithMany("UploadedBatches")
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("ClinicalIntelligence.Api.Domain.Models.DocumentChunk", b =>
                {
                    b.HasOne("ClinicalIntelligence.Api.Domain.Models.Document", "Document")
                        .WithMany("DocumentChunks")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("ClinicalIntelligence.Api.Domain.Models.DocumentReference", b =>
                {
                    b.HasOne("ClinicalIntelligence.Api.Domain.Models.Patient", "Patient")
                        .WithMany("DocumentReferences")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("ClinicalIntelligence.Api.Domain.Models.Encounter", b =>
                {
                    b.HasOne("ClinicalIntelligence.Api.Domain.Models.Patient", "Patient")
                        .WithMany("Encounters")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("ClinicalIntelligence.Api.Domain.Models.EntityCitation", b =>
                {
                    b.HasOne("ClinicalIntelligence.Api.Domain.Models.DocumentChunk", "DocumentChunk")
                        .WithMany("EntityCitations")
                        .HasForeignKey("DocumentChunkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicalIntelligence.Api.Domain.Models.ExtractedEntity", "ExtractedEntity")
                        .WithMany("EntityCitations")
                        .HasForeignKey("ExtractedEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentChunk");

                    b.Navigation("ExtractedEntity");
                });

            modelBuilder.Entity("ClinicalIntelligence.Api.Domain.Models.ErdConflict", b =>
                {
                    b.HasOne("ClinicalIntelligence.Api.Domain.Models.ErdPatient", "Patient")
                        .WithMany("Conflicts")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_conflicts_patient_id");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("ClinicalIntelligence.Api.Domain.Models.ExtractedEntity", b =>
                {
                    b.HasOne("ClinicalIntelligence.Api.Domain.Models.Document", "Document")
                        .WithMany("ExtractedEntities")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicalIntelligence.Api.Domain.Models.ErdPatient", "Patient")
                        .WithMany("ExtractedEntities")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_extracted_entities_patient_id");

                    b.HasOne("ClinicalIntelligence.Api.Domain.Models.User", "VerifiedByUser")
                        .WithMany("VerifiedEntities")
                        .HasForeignKey("VerifiedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Document");

                    b.Navigation("Patient");

                    b.Navigation("VerifiedByUser");
                });

            modelBuilder.Entity("ClinicalIntelligence.Api.Domain.Models.MedicationStatement", b =>
                {
                    b.HasOne("ClinicalIntelligence.Api.Domain.Models.Patient", "Patient")
                        .WithMany("MedicationStatements")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("ClinicalIntelligence.Api.Domain.Models.Observation", b =>
                {
                    b.HasOne("ClinicalIntelligence.Api.Domain.Models.Encounter", "Encounter")
                        .WithMany("Observations")
                        .HasForeignKey("EncounterId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ClinicalIntelligence.Api.Domain.Models.Patient", "Patient")
                        .WithMany("Observations")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Encounter");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("ClinicalIntelligence.Api.Domain.Models.PasswordResetToken", b =>
                {
                    b.HasOne("ClinicalIntelligence.Api.Domain.Models.User", "User")
                        .WithMany("PasswordResetTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClinicalIntelligence.Api.Domain.Models.Procedure", b =>
                {
                    b.HasOne("ClinicalIntelligence.Api.Domain.Models.Encounter", "Encounter")
                        .WithMany("Procedures")
                        .HasForeignKey("EncounterId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ClinicalIntelligence.Api.Domain.Models.Patient", "Patient")
                        .WithMany("Procedures")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Encounter");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("ClinicalIntelligence.Api.Domain.Models.ProcessingJob", b =>
                {
                    b.HasOne("ClinicalIntelligence.Api.Domain.Models.Document", "Document")
                        .WithMany("ProcessingJobs")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("ClinicalIntelligence.Api.Domain.Models.Session", b =>
                {
                    b.HasOne("ClinicalIntelligence.Api.Domain.Models.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClinicalIntelligence.Api.Domain.Models.VectorQueryLog", b =>
                {
                    b.HasOne("ClinicalIntelligence.Api.Domain.Models.ErdPatient", "Patient")
                        .WithMany("VectorQueryLogs")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ClinicalIntelligence.Api.Domain.Models.User", "User")
                        .WithMany("VectorQueryLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Patient");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClinicalIntelligence.Api.Domain.Models.BillingCodeCatalogItem", b =>
                {
                    b.Navigation("CodeSuggestions");
                });

            modelBuilder.Entity("ClinicalIntelligence.Api.Domain.Models.Document", b =>
                {
                    b.Navigation("DocumentChunks");

                    b.Navigation("ExtractedEntities");

                    b.Navigation("ProcessingJobs");
                });

            modelBuilder.Entity("ClinicalIntelligence.Api.Domain.Models.DocumentBatch", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("ClinicalIntelligence.Api.Domain.Models.DocumentChunk", b =>
                {
                    b.Navigation("EntityCitations");
                });

            modelBuilder.Entity("ClinicalIntelligence.Api.Domain.Models.Encounter", b =>
                {
                    b.Navigation("Conditions");

                    b.Navigation("Observations");

                    b.Navigation("Procedures");
                });

            modelBuilder.Entity("ClinicalIntelligence.Api.Domain.Models.ErdConflict", b =>
                {
                    b.Navigation("Resolution");
                });

            modelBuilder.Entity("ClinicalIntelligence.Api.Domain.Models.ErdPatient", b =>
                {
                    b.Navigation("CodeSuggestions");

                    b.Navigation("Conflicts");

                    b.Navigation("DocumentBatches");

                    b.Navigation("Documents");

                    b.Navigation("ExtractedEntities");

                    b.Navigation("VectorQueryLogs");
                });

            modelBuilder.Entity("ClinicalIntelligence.Api.Domain.Models.ExtractedEntity", b =>
                {
                    b.Navigation("CodeSuggestions");

                    b.Navigation("EntityCitations");
                });

            modelBuilder.Entity("ClinicalIntelligence.Api.Domain.Models.Patient", b =>
                {
                    b.Navigation("Conditions");

                    b.Navigation("DocumentReferences");

                    b.Navigation("Encounters");

                    b.Navigation("MedicationStatements");

                    b.Navigation("Observations");

                    b.Navigation("Procedures");
                });

            modelBuilder.Entity("ClinicalIntelligence.Api.Domain.Models.Session", b =>
                {
                    b.Navigation("AuditLogEvents");
                });

            modelBuilder.Entity("ClinicalIntelligence.Api.Domain.Models.User", b =>
                {
                    b.Navigation("AuditLogEvents");

                    b.Navigation("CodeDecisions");

                    b.Navigation("ConflictResolutions");

                    b.Navigation("PasswordResetTokens");

                    b.Navigation("Sessions");

                    b.Navigation("UploadedBatches");

                    b.Navigation("UploadedDocuments");

                    b.Navigation("VectorQueryLogs");

                    b.Navigation("VerifiedEntities");
                });
#pragma warning restore 612, 618
        }
    }
}
