// <auto-generated />
using System;
using ClinicalIntelligence.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ClinicalIntelligence.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260115150000_US038_CaseInsensitiveUserEmailUniqueConstraint")]
    partial class US038_CaseInsensitiveUserEmailUniqueConstraint
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            // Note: This is a partial snapshot focusing on the User entity with citext Email column.
            // The full model is maintained in ApplicationDbContextModelSnapshot.cs
#pragma warning restore 612, 618
        }
    }
}
